### PR TITLE
Allow validating PropertySerializers

### PR DESCRIPTION
**Pull request by stefanor**
The `errors` property wasn't returning anything.

### CODE REVIEW

**Comment by zoidbergwill** [comment]
:+1:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by adrianmoisey** [comment]
(ignore the failed tests, I tried to add them, but that isn't working. https://github.com/yola/drf-madprops/issues/12)

**Comment by stefanor** [comment]
@RayeN: You OK with the test suite hackery?

**Comment by RayeN** [comment]
Yup, looks ok to me.

**Pull request merged**
